# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: fdafec9b6b9c78eb6102a336c9d2210cc2c40b4c66e1e9e049cc0cc7655a79cadf65470258f6514865f46d570976acf139cd6bfdf335a0ff2e03c7e3f7bc5dcc

test:
  secret_key_base: 4f2e6a66e56b8769a19cd909b0c0e563f893310ce7d65d1966a87b34baa7b2f2dc5f220cd2ffd51d110b416a041c47dc309d8b0f8ab66d6da2328a9ffdd722b7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
